### ISSUE TITLE
Uncaught Error: 'ui-variables.less' wasn't found

### ISSUE THREAD

**Issue by fojt-cz** [freshl/atom-compile-less#12]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [atom-compile-less](https://github.com/freshl/atom-compile-less) package, v0.12.0

### Stack Trace

Uncaught Error: 'ui-variables.less' wasn't found

```
At C:\Users\martin\.atom\packages\atom-compile-less\lib\atom-compile-less.js:36

Error
  at new Parser (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\less-cache\node_modules\less\lib\less\parser.js:333:27)
  at C:\Users\martin\.atom\packages\atom-compile-less\lib\atom-compile-less.js:29:14
  at fs.readFile.read (C:\Users\martin\.atom\packages\atom-compile-less\lib\atom-compile-less.js:16:12)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

### Commands

```
     -0:10.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:08.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "SFTP-deployment",
      "ctags-status",
      "tree-view-open-files",
      "Remote-FTP",
      "coffee-compiler",
      "git-plus",
      "sass-compiler",
      "remote-sync",
      "example",
      "language-smarty"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-compile-less, v0.12.0
file-icons, v1.5.8
flex-tool-bar, v0.4.2
language-smarty-php, v0.5.0
less-compiler, v0.6.2
linter, vundefined
linter-coffeelint, v0.3.2
linter-less, v2.0.3
open-recent, v2.2.4
php-class-tree, vundefined
project-manager, v1.15.10
project-view, v0.1.2
sass-autocompile, v0.7.1
symbols-tree-view, v0.9.3
tool-bar, v0.1.8
tool-bar-main, v0.0.8
tree-view-finder, v0.2.1
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by oneDoTsix18** [comment]
How decid this problem?
