### ISSUE TITLE
Uncaught ReferenceError: err is not defined

### ISSUE THREAD

**Issue by feh-wilinando** [freshl/atom-compile-less#3]
/Users/Nando/.atom/packages/atom-compile-less/lib/atom-compile-less.coffee:25

**Comment by charlieryan** [comment]
Also having this issue, here's the Stack Trace:

    /Users/charlieryan/.atom/packages/atom-compile-less/lib/atom-compile-less.js:27

    ReferenceError: err is not defined
        at /Users/charlieryan/.atom/packages/atom-compile-less/lib/atom-compile-less.js:27:13
        at fs.readFile.read (/Users/charlieryan/.atom/packages/atom-compile-less/lib/atom-compile-less.js:16:12)
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
