### ISSUE TITLE
Uncaught Error: Unrecognised Input

### ISSUE THREAD

**Issue by fpcorso** [freshl/atom-compile-less#5]
I received this error:
Uncaught Error: Unrecognised input
C:\Users\Frank\.atom\packages\atom-compile-less\lib\atom-compile-less.coffee:28

Stack trace:
Error
  at new Parser (C:\Users\Frank\AppData\Local\atom\app-0.182.0\resources\app\node_modules\less-cache\node_modules\less\lib\less\parser.js:333:27)
  at C:\Users\Frank\.atom\packages\atom-compile-less\lib\atom-compile-less.coffee:26:18
  at fs.readFile.read (C:\Users\Frank\.atom\packages\atom-compile-less\lib\atom-compile-less.coffee:16:5)
  at fs.js:337:14
  at FSReqWrap.oncomplete (fs.js:100:15)

What it said:
The error was thrown from the atom-compile-less package. You can help by creating an issue. Please explain what actions triggered this error.

I just installed this package. I created a .less file and then saved. I received a Uncaught Error: ENOENT message that said it was related to Atom which I created an issue for in their repository here: https://github.com/atom/atom/issues/5746  However, the file still saved, so I thought it must be an issue with Atom. However, a few saves later, and now I am receiving this error along with the ENOENT and now the file is not saving.

**Comment by fpcorso** [comment]
Also, I do not know if it is related but I got this warning too for this package:

atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.

Called 1 time
Atom.Object.defineProperty.get - C:\Users\Frank\AppData\Local\atom\app-0.182.0\resources\app\src\atom.js:54:11
Object.activate - C:\Users\Frank\.atom\packages\atom-compile-less\lib\atom-compile-less.coffee:77:9

**Comment by fpcorso** [comment]
OS: Windows 7
Atom: 0.182.0 --says latest version when checking for updates

The only errors listed in the dev tools are the two shown here.
No errors are shown when saving the .less in safe mode
